version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    environment:
      - SOURCE_BRANCH: master
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Test
          command: |
            docker build -t bio3:test . -f Dockerfile.test
            docker run bio3:test
      - deploy:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then 
              docker build -t bio3:latest . 
              docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
              docker tag bio3 $DOCKER_HUB_USER_ID/bio3:$CIRCLE_SHA1
              docker tag bio3 $DOCKER_HUB_USER_ID/bio3:latest
              docker push $DOCKER_HUB_USER_ID/bio3:$CIRCLE_SHA1
              docker push $DOCKER_HUB_USER_ID/bio3:latest
            fi
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then 
              scp -o StrictHostKeyChecking=no -r deploy_app.sh $DIGITALOCEAN_USER@ahmet.se:/usr/src/deploy_app.sh
              ssh -o StrictHostKeyChecking=no $DIGITALOCEAN_USER@ahmet.se "/bin/bash /usr/src/deploy_app.sh ayildirim/bio3:latest"
            fi
